# Generated by Django 3.2.3 on 2022-03-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=50)),
                ('car_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_bodytype', models.CharField(max_length=50)),
                ('car_fueltype', models.CharField(max_length=50)),
                ('car_transmission', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('car_brand', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartypes', to='carviewer.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('car_bodytype', models.CharField(max_length=50)),
                ('car_expert_review', models.CharField(max_length=100)),
                ('car_user_review', models.CharField(max_length=100)),
                ('car_overall_review', models.CharField(max_length=100)),
                ('car_brand', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreviews', to='carviewer.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_year', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('car_bodytype', models.CharField(max_length=50)),
                ('car_fueltype', models.CharField(max_length=50)),
                ('car_transmission', models.CharField(max_length=50)),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_mileage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_brand', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='carmodels', to='carviewer.carbrand')),
            ],
        ),
    ]
