# Generated by Django 3.2.3 on 2022-04-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0002_auto_20220414_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='car_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='carreview',
            name='car_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cartype',
            name='car_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
