# Generated by Django 3.2.3 on 2022-04-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carviewer', '0004_alter_carbrand_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartype',
            name='car_image',
            field=models.ImageField(blank=True, upload_to='car_image/%Y/%M/%D'),
        ),
    ]
